AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false
